- hosts: all
  become: yes

  vars:
    user: zeestrat
    uid: 10000
    group: staff

  tasks:
    # Setup user
    - name: Create user
      user: 
        name: "{{ user }}"
        uid: "{{ uid }}"
        group: "{{ group }}"
        groups: "lxd,sudo"
        append: yes
        shell: /bin/bash
        password: "$6$9VnD4IIu10$7kBHJd8dvO0pDZgaP08xn/EmL9H.2Lz1jY2zxW304RQnF6GQH722f97IszmaZ2YTJehUscRreP8y8WmsKhqBj1"

    - name: Add pubkey
      authorized_key:
        user: "{{ user }}"
        key: "{{ lookup('file', '/Users/profile/.ssh/id_rsa.pub') }}"

    - name: Copy bashrc and profile from vagrant user
      command: "cp /home/vagrant/{{ item }} /home/{{ user }}/{{ item }}"
      args:
        creates: "/home/{{ user }}/{{ item }}"
      with_items:
        - .bashrc
        - .profile

    - name: Set permissions of bashrc and profile
      file:
        path: "/home/{{ user }}/{{ item }}"
        owner: "{{ user }}"
        group: "{{ group }}"
      with_items:
        - .bashrc
        - .profile

    - name: Set permissions of home
      file:
        path: "/home/{{ user }}"
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: Add `watch-juju` alias and snap path to .bashrc
      blockinfile:
        path: "/home/{{ user }}/.bashrc"
        content: |
          # Add alias for easy watching of juju status
          alias watch-juju='watch --color -n1 juju status --color'
          # Add snaps to path
          export PATH=/snap/bin:$PATH

    - name: Install packages
      apt:
        name: ["zfsutils-linux", "apt-cacher-ng", "python3", "python3-pip", "lxd", "lxd-client"]
        state: latest
        default_release: xenial-backports

    - name: Install juju 2.4/stable snap
      command: snap install juju --classic --channel=2.4/stable

    - name: Run juju to generate juju dir
      command: /snap/bin/juju
      become_user: "{{ user }}"
      args:
        creates: ~/.local/share/juju

    - name: Setup lxd
      command: "{{ item }}"
      with_items:
        - lxd init --auto --storage-backend zfs --storage-create-loop 30 --storage-pool lxd
        - lxc network set lxdbr0 ipv6.address none
      ignore_errors: yes

    - name: Configure apt-cacher-ng for https
      lineinfile:
        path: /etc/apt-cacher-ng/acng.conf
        line: 'PassThroughPattern: .*'

    - name: Restart apt-cacher-ng
      service:
        name: apt-cacher-ng
        state: restarted

    - name: Add apt proxy to juju config
      blockinfile:
        path: "/home/{{ user }}/.local/share/juju/clouds.yaml"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0600
        create: yes
        content: |
          clouds:
            lxd:
              type: lxd
              config:
                apt-http-proxy: http://{{ ansible_default_ipv4.address }}:3142
                apt-https-proxy: http://{{ ansible_default_ipv4.address }}:3142
                enable-os-upgrade: false
