- hosts: all
  become: yes
  vars:
    user: zeestrat
    uid: 10000
    group: staff
    home_files:
      - .bashrc
      - .profile
    juju_channel: 2.7/stable
    charm_channel: latest/stable
  tasks:
    - name: Set timezone to Europe/Oslo
      timezone:
        name: Europe/Oslo

    - name: Create "{{ user }}" user
      user: 
        name: "{{ user }}"
        uid: "{{ uid }}"
        group: "{{ group }}"
        groups: lxd,sudo
        append: yes
        skeleton: /etc/skel
        shell: /bin/bash

    - name: Get vagrant authorized keys
      slurp:
        src: /home/vagrant/.ssh/authorized_keys
      register: authorized_keys

    - name: Add authorized key to "{{ user }}"
      authorized_key:
        user: "{{ user }}"
        key: "{{ authorized_keys.content | b64decode }}"

    - name: Copy home files from skeleton
      command: "cp /etc/skel/{{ item }} /home/{{ user }}/{{ item }}"
      args:
        creates: "/home/{{ user }}/{{ item }}"
      with_items: "{{ home_files }}"

    - name: Set permissions of home files
      file:
        path: "/home/{{ user }}/{{ item }}"
        owner: "{{ user }}"
        group: "{{ group }}"
      with_items: "{{ home_files }}"

    - name: Set permissions of home
      file:
        path: "/home/{{ user }}"
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: Add `watch-juju` alias and snap path to .bashrc
      blockinfile:
        path: "/home/{{ user }}/.bashrc"
        content: |
          # Add alias for easy watching of juju status
          alias watch-juju='watch --color -n1 juju status --relations --color'
          # Add alias for bootstrapping juju
          alias bootstrap-juju='juju bootstrap lxd --no-gui'
          # Add alias for bootstrapping juju with apt proxy
          alias bootstrap-juju-proxy='juju bootstrap lxd --no-gui --model-default config.yaml'
          # Add snaps to path
          export PATH=/snap/bin:$PATH

    - name: Create ./local/bin directory
      file:
        path: "/home/{{ user }}/{{ item }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ group }}"
      loop:
        - .local
        - .local/bin

    - name: Create juju-port-forward plugin
      copy:
        dest: "/home/{{ user }}/.local/bin/juju-port-forward"
        mode: "0755"
        content: |
          #!/usr/bin/env bash
          juju ssh $1 -L 0.0.0.0:$2:localhost:$3


    - name: Install apt packages for Ubuntu Xenial 16.04
      apt:
        name: 
          - lxd
          - zfsutils-linux
          - bash-completion
          - apt-cacher-ng
          - python-tox
          - python3
          - python3-pip
          - docker.io
          - docker-compose
        state: latest
        default_release: xenial-backports
      when: ansible_distribution_release == 'xenial'

    - name: Install apt packages for Ubuntu Bionic 18.04
      apt:
        name:
          - lxd
          - zfsutils-linux
          - bash-completion
          - apt-cacher-ng
          - python-tox
          - python3-pip
          - docker.io
          - docker-compose
        state: latest
      when: ansible_distribution_release == 'bionic'

    - name: Add "{{ user }}" to docker group
      user:
        name: "{{ user }}"
        groups: docker
        append: yes

    - name: Install charm "{{ charm_channel }}" snap
      command: "snap install charm --classic --channel={{ charm_channel }}"
      args:
        creates: /snap/charm

    - name: Install juju "{{ juju_channel }}" snap
      command: "snap install juju --classic --channel={{ juju_channel }}"
      args:
        creates: /snap/juju

    - name: Run juju to generate juju dir
      command: /snap/bin/juju
      become_user: "{{ user }}"
      args:
        creates: ~/.local/share/juju

    - name: Setup lxd
      command: "{{ item }}"
      with_items:
        - lxd init --auto --storage-backend zfs --storage-create-loop 30 --storage-pool lxd
        - lxc network set lxdbr0 ipv6.address none
      ignore_errors: yes

    - name: Configure apt-cacher-ng for https
      lineinfile:
        path: /etc/apt-cacher-ng/acng.conf
        line: 'PassThroughPattern: .*'
      notify: restart apt-cacher-ng

    - name: Template juju config for apt cache and speeding up dev
      blockinfile:
        path: "/home/{{ user }}/config.yaml"
        owner: "{{ user }}"
        group: "{{ group }}"
        create: yes
        content: |
          enable-os-upgrade: false
          apt-http-proxy: {{ ansible_default_ipv4.address }}:3142
          apt-https-proxy: {{ ansible_default_ipv4.address }}:3142

  handlers:
    - name: restart apt-cacher-ng
      service:
        name: apt-cacher-ng
        state: restarted
