- hosts: all
  become: yes

  vars:
    user: zeestrat
    uid: 10000
    group: staff

  tasks:
    # Setup user
    - name: Create user
      user: 
        name: "{{ user }}"
        uid: "{{ uid }}"
        group: "{{ group }}"
        groups: "lxd,sudo"
        append: yes
        shell: /bin/bash
        password: "$6$9VnD4IIu10$7kBHJd8dvO0pDZgaP08xn/EmL9H.2Lz1jY2zxW304RQnF6GQH722f97IszmaZ2YTJehUscRreP8y8WmsKhqBj1"

    - name: Add pubkey
      authorized_key:
        user: "{{ user }}"
        key: "{{ lookup('file', '/Users/profile/.ssh/id_rsa.pub') }}"

    - name: Copy bashrc and profile from vagrant user
      command: "cp /home/vagrant/{{ item }} /home/{{ user }}/{{ item }}"
      args:
        creates: "/home/{{ user }}/{{ item }}"
      with_items:
        - .bashrc
        - .profile

    - name: Set permissions of bashrc and profile
      file:
        path: "/home/{{ user }}/{{ item }}"
        owner: "{{ user }}"
        group: "{{ group }}"
      with_items:
        - .bashrc
        - .profile

    - name: Set permissions of home
      file:
        path: "/home/{{ user }}"
        owner: "{{ user }}"
        group: "{{ group }}"

    - name: Add things to profile
      blockinfile:
        path: "/home/{{ user }}/.bashrc"
        content: |
          # Juju
          alias watch-juju='watch --color -n1 juju status --color'

          # Charms
          export JUJU_REPOSITORY=$HOME/dev/charms
          export LAYER_PATH=$JUJU_REPOSITORY/layers
          export INTERFACE_PATH=$JUJU_REPOSITORY/interfaces

          # Add snaps to path
          export PATH=/snap/bin:$PATH


    # Setup packages
    - name: Add repos
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - ppa:rael-gc/rvm

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - zfs
        - python-pip
        - python-tox
        - rvm
        - bash-completion
        - tree
        - apt-cacher-ng

    - name: Install LXD
      apt:
        name: "{{ item }}"
        state: latest
        default_release: xenial-backports
      with_items:
        - lxd
        - lxd-client

    - name: Install juju snap
      command: snap install juju --classic

    - name: Install charm snap
      command: snap install charm

    # Setup LXD
    - name: Setup LXD
      command: "{{ item }}" 
      with_items:
        - lxd init --auto --storage-backend zfs --storage-create-loop 30 --storage-pool lxd
        - lxc network create lxdbr0
        - lxc network attach-profile lxdbr0 default eth0
        - lxc network set lxdbr0 ipv6.address none
      # environment:
      #   PATH: "/snap/bin:{{ ansible_env.PATH }}"
      ignore_errors: yes


    # Setup charm tools
    - name: Run charm version to generate snap dir
      command: /snap/bin/charm
      become_user: "{{ user }}"
      args:
        creates: ~/snap/charm/

    - name: Make sure charm tools dir is present
      file:
        path: ~/snap/charm/current/.local/share/juju
        state: directory
      become_user: "{{ user }}"

    - name: Copy charm store token
      command: cp ~/dev/secrets/store-usso-token-szeestraten ~/snap/charm/current/.local/share/juju/store-usso-token
      become_user: "{{ user }}"
      args:
        creates: ~/snap/charm/current/.local/share/juju/store-usso-token

    - name: Login to charm store
      command: /snap/bin/charm login
      become_user: "{{ user }}"


    # Setup Juju
    - name: Run juju to generate juju dir
      command: /snap/bin/juju
      become_user: "{{ user }}"
      args:
        creates: ~/.local/share/juju

    - name: Add juju lxd cloud config
      blockinfile:
        path: "/home/{{ user }}/.local/share/juju/clouds.yaml"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0600
        create: yes
        content: |
          clouds:
            lxd:
              type: lxd
              config:
                apt-http-proxy: http://{{ ansible_default_ipv4.address }}:3142
                apt-https-proxy: http://{{ ansible_default_ipv4.address }}:3142
                enable-os-upgrade: false

